### ISSUE TITLE
Fix updatecli manifest for tracking Maven version

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/docker-inbound-agents#18]
- This manifest is using deprecated syntax and as such, it fails to open PR for new Maven version
- Also: https://github.com/jenkins-infra/jenkins-infra/issues/2100. Since we want to deploy a new Maven version on ci.jenkins.io for containers, VM and tools at the same time, could be nice to get the Maven version from the "VM template" as reference (e.g. retrieve the version of the azure VM template used in production _right now_  for ci.jenkins.io in the hieradata/common.yaml, and use it to retrieve the maven version used for this VM template version in packer_image).

**Comment by lemeurherve** [comment]
Resolved by https://github.com/jenkins-infra/docker-inbound-agents/pull/67
